### ISSUE TITLE
Multiple processes

### ISSUE THREAD

**Issue by insomnix** [Jako/CronManager#14]
I have multiple cron jobs. Some run every 15 minutes, others run once a day. Some of those once a day cron jobs takes more than 15 minutes to run. So what sometimes happens is that it will run that job twice because the "next run" doesn't update until after the cron job runs. What I think we need is the "next run" to update first or some sort of block placed on that job if it is already running.

**Comment by Jako** [comment]
Each cronjob needs a started column with a boolean value.

**Comment by wfoojjaec** [comment]
You can use `flock` on linux systems to block simultaneous execution of cron.php
Works well for my projects.

**Comment by Jako** [comment]
Nice idea, but what happens, when the cron job crashes or runs in a time limit? Then we could use a register_shutdown_function to clear those locks that are not removed automatically.

**Comment by wfoojjaec** [comment]
I assume, it is partially resolved via https://github.com/Jako/CronManager/pull/46

**Comment by Jako** [comment]
This is added in 1.4.0. Please check the 1.4.0-rc1 in https://github.com/Jako/CronManager/tree/master/_packages
