### ISSUE TITLE
bug/feature: Inactive jobs run once when they've never run before

### ISSUE THREAD

**Issue by brueli** [Jako/CronManager#21]
I found a bug in the job selection part of cron.php. But it could also be named a feature.

The job selection conditions in cron.php seem not correct.
Job's which never ran before are running once when cron.php is called, even when the jobs are inactive.

I propose to change assets/components/cronmanager/cron.php line 17-21 into:
$cronjobs = $modx->getCollection('modCronjob', array(
    array('nextrun' => null,
    'OR:nextrun:<=' => $rundatetime),
    'AND:active:=' => true,
));

By this the job selection criteria will be working correctly.

**Comment by Jako** [comment]
Fixed with 1.1.0
