### ISSUE TITLE
Job is not starting at all

### ISSUE THREAD

**Issue by Camo30** [Jako/CronManager#23]
Hi @Jako,

thank you for keeping this extra updated :+1:

After using the previous version 1.1.0pl for a long time i tried an upgrade to the new one.

But there are some strange happenings with it: while installing the first 1.2.0 version there was an error indicating that its trying (and failing) to install another extra "crosslinks" - it seems that there is a package dependency while its not in the package description. Without that extra the cron manager does not work at all and shows nothing but an error in the log. After installing that additional extra the manager works, as i can add, edit and delete some jobs. But now the cron job (cron.php) does nothing while there is still an active job, no output, no error, nothing.

I have also tried to upgrade to the latest release 1.2.0pl2 but the problem is still the same. Now I restored to the previously installed version 1.1.0pl and it works again.

**Comment by Jako** [comment]
Are there any errors in the MODX error log?

**Comment by Camo30** [comment]
No, unfortunately not.

**Comment by Jako** [comment]
It works fine on my developing machine.

Do you use a webcronjob or do you call it directly with `php https://extras.treehillstudio.local/develop/cronmanager/assets/components/cronmanager/cron.php` in the crontab? If you use it as webcronjob, please be sure that you have added the `cronjob_id=xxx` property (see https://jako.github.io/CronManager/usage/). There is also a cronmanager.debug setting in the system settings, that will log a line, when a cronjob is executed.

**Comment by Camo30** [comment]
Its a webcronjob, and thank you - it seems that was the issue, i forgot to add the `cronjob_id` property. My bad, sorry. 

If I may give a suggestion for a new feature, there was this code in the previous version:
``` PHP
$rundatetime = date('Y-m-d H:i:s');
echo $rundatetime;
```

With the code refactoring the `echo` was getting removed, so now when running the webcronjob the response is empty. Previously there was this timestamp to know that it runs successfully.

**Comment by Jako** [comment]
It seems that his line was added by someone else. This repo never had this line: https://github.com/Jako/CronManager/commits/master/assets/components/cronmanager/cron.php. But I will log some debug information, if the cronjob_id is not equal to the system setting.
