### ISSUE TITLE
Subfolder/multi-domain support

### ISSUE THREAD

**Issue by DizeroNL** [Jako/CronManager#25]
I just tried for the first time to use the Extra. But because the config.core.php is looked for in a specific place on line 10 of connector.php, as shown here...
`require_once dirname(dirname(dirname(dirname(__FILE__)))) . '/config.core.php';`
..it won't work with my personal setup, where the MODX install is more of an API than the actual website.

My context containing the data is in a subfolder, so making line 10 read this:
`require_once dirname(dirname(dirname(dirname(__FILE__)))) . '/data/config.core.php';`
will do the trick. However, on an update this will clearly be overwritten again, causing the whole thing to break down, if I don't think about it.

Clearly, I'll be in a minority here anyways, and I suppose I _could_ just leave an otherwise unused config.core.php in the folder it is looked for. But I feel a simple textfield where you can customize the path to the config file would do the trick.

You can still set the default path to /config.core.php (and doing the redirecting to the root folder the way it's done now), but allowing users to harden their installations the way they see fit seems like the more flexible option to me.

**Comment by Jako** [comment]
All Extras that I know (I currently have checked Babel, ClientConfig, Collections …) refer to a config.core.php one level above the `assets` folder in their connectors. So I close this as `wontfix`.
