### ISSUE TITLE
Make cronjob GRid sortable

### ISSUE THREAD

**Issue by pepebe** [Jako/CronManager#27]
Clicking the columns doesn't change the sortorder.

This is important if you have multiple cronjobs und you want to see the order they are fired.

<img width="889" alt="grafik" src="https://user-images.githubusercontent.com/667315/87391043-4de22580-c5aa-11ea-9d00-709931c1f8fb.png">

Cheers!

**Comment by Jako** [comment]
This is added in 1.3.0
