### ISSUE TITLE
CronManager only executes one snippet/cronjob at a time

### ISSUE THREAD

**Issue by travisbotello** [Jako/CronManager#32]
**Summary**
Creating a cronjob that runs every minute blocks all other cronjobs.

**Steps to reproduce the issue**
- setup at least two cronjobs with an interval of 1 minute
- execute cron.php via Url or Shell

**Expected behavior**
- All cronjobs that are scheduled for the upcoming interval should be executed

**What do you see instead**
- Only one cronjob is executed while the rest is pending

In my particular example `updateCurrentPrice` always gets executed when calling `cron.php` while `revokeAccess` is pending and never executed.

I am not sure if this is expected behavior but my assumption was that CronManager is acting like a queue here and runs multiple jobs on `cron.php` if they are pending for execution. Currently the only fix for this is to never set a 1 minute interval for any job. The lowest you can go is 2 minutes so that there is always a "free" spot in the `cron.php` execution for any outstanding job.

<img width="902" alt="Bildschirmfoto 2021-02-20 um 10 14 10" src="https://user-images.githubusercontent.com/1157380/108590546-68f8ed00-7364-11eb-8f0c-5adb835c6eb7.png">

**Comment by Jako** [comment]
This is fixed with 1.2.3.
