### ISSUE TITLE
Updating cronjobs from grid throws an error

### ISSUE THREAD

**Issue by MaticSulc** [Jako/CronManager#59]
While attempting to update cronjobs from the grid, an error is thrown: `Requested processor not found`.
The processor getting called is (`mgr/cronjobs/updateFromGrid`) .

Reproduced on MODX 3.0.4-pl.

**Comment by Jako** [comment]
Please upload the current [cronmanager.min.js](https://github.com/Jako/CronManager/blob/master/assets/components/cronmanager/js/mgr/cronmanager.min.js) to your installation to fix the issue until the next version of CronManager will be released.

**Comment by Jako** [comment]
Fixed with 1.3.1
