### ISSUE TITLE
No snippet return in the combo-box

### ISSUE THREAD

**Issue by phron** [Jako/CronManager#8]
Hello
Using either Revo2.2 and Revo2.3 for both I entounter a problem with CronManager that does not list the snippets...
No error in the log ,(neither in modx log or apache log) ...
Hope you can do something I really need CronManager as prerequesite for use with GroupEletters
Thanks

Is there a version for revo2.3? 
Cheers

**Comment by Jako** [comment]
Should be fixed with 1.2.0
